[project]
name = "cola-inference"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pytorch-lightning>=2.1.0",
    "transformers>=4.40.0",
    "datasets>=3.2.0",
    "numpy>=2.2.0,<2.3.0",
    "scipy>=1.11.0",
    "onnx>=1.20.0",
    "onnxruntime>=1.19.0",
    "scikit-learn>=1.5.2",
    "hydra-core",
    "omegaconf",
    "hydra_colorlog",
    "fastapi",
    "uvicorn",
    "torch>=2.0.0",
]
