version: "3"
services:
    prediction_api:
        build:
            context: ..
            dockerfile: deploy/Dockerfile
        container_name: "inference_container"
        ports:
            - "8000:8000"