services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.01-py3
    container_name: triton_server
    ports:
      - "8000:8000"   # HTTP inference
      - "8001:8001"   # gRPC inference
      - "8002:8002"   # Prometheus metrics
    volumes:
      - ./model_repository:/models
    command: >
      tritonserver
      --model-repository=/models
      --log-verbose=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
