name: "cola_postprocess"
backend: "python"
max_batch_size: 128

input [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

output [
  {
    name: "label"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "score"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 8, 16, 32, 64 ]
  max_queue_delay_microseconds: 100
}

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
